wandb_active: true
wandb_project_name: codon_transformer
wandb_entity_name: gene_mdh_gan
checkpoint_dir: patric_2.5B_pretraining/checkpoints_v2/
tokenizer_file: ../../genslm/tokenizer_files/codon_wordlevel_69vocab.json
train_file: /path/to/data/patric_89M/pgfam_30k_h5_tts/combined_train.h5
val_file: /path/to/data/patric_89M/pgfam_30k_h5_tts/combined_val.h5
test_file: /path/to/data/patric_89M/pgfam_30k_h5_tts/combined_test.h5
model_config_json: ../../genslm/architectures/neox/neox_2,533,931,008.json
checkpoint_every_n_train_steps: 2500
log_every_n_steps: 250
num_nodes: 128
batch_size: 1
block_size: 2048
epochs: 50
num_data_workers: 16
prefetch_factor: 16